# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96563987a5f5f83a3233fa624053bbf63ceaa4dcfc95137cdcea8d0cb267dc134d5a839f74ab6a31936a68903f1b8fbc1117842072d9d6cd4ae8313293fc4891

test:
  secret_key_base: 22fd10cdbd7885f316135c31044cfae4148da9c53730b1958db7e1bb9191928e497188bb0f37887c56bc49be91e85bb549945f14346e7712174946050b59baf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
